#!/bin/bash

exercises=( [0]="Plank" [1]="Stepping" [2]="Side Stepping" [3]="Left Side Hold" [4]="Right Side Hold" )

limit=`expr $1 - 1`

if [ $limit -gt ${#exercises} ]; then
	echo "Too long only ${#exercises} exercises"
	exit
fi

espeak "Get ready"
sleep 3
espeak 3
sleep 0.5
espeak 2
sleep 0.5
espeak 1
sleep 1.0

for i in `seq 0 $limit`
do
	espeak "${exercises[ $i ]}" &

	sleep 50
	xkbbell &
	sleep 8
	xkbbell &
	sleep 1
	xkbbell &
	sleep 1
done

espeak "Finished"

